### ISSUE TITLE
Allow single click on Dock items (DockClickPolicy)

### ISSUE THREAD

**Issue by probonopd** [gnustep/apps-gworkspace#10]
Please allow for single click on Dock items as a configuration option as it has been implemented by @BertrandDekoninck.

This is important for users who would like to make GWorkspace behave more Mac-like.

Check everything related to DockClickPolicy in
https://github.com/gnustep/apps-gworkspace/compare/master...BertrandDekoninck:master

Thank you very much for your kind consideration.

**Comment by BertrandDekoninck** [comment]
For this, I should prepare a dedicated PR from a clean GWorkspace branch because my branch of GWorkspace was borched when GNUstep switched from SVN to GIT in 2017 and claims to have more than 2400 commits although it's only a few lines of code different from master. And I never bothered to find how to  to fix that count.

**Comment by probonopd** [comment]
Yes, it would be great if you could send a PR @BertrandDekoninck. Highly appreciated. Thanks for your time!

**Comment by rmottola** [comment]
I'll think about this, I am not sure I will accept a PR.. GWorkspace doesn't aim to be a Finder clone, more a Workspace reincarnation, also I am not a fan of adding too many options, since preferences should remain terse.
But let's see when Bertrand cleans up his branch.

**Comment by BertrandDekoninck** [comment]
Hello Riccardo ! 

Here is a patch coming from my fork of gworkspace. It allows single click in the dock by adding 
"defaults write GWorkspace dockclickpolicy 1" in a terminal.
You can revert to the default double click behaviour either by deleting this defaults key or by typing
"defaults write GWorkspace dockclickpolicy 2"

It's no more visible than that in the UI.

It works well for me, despite the fact that if you click two times in a row on a dock icon, you get a warning dialog saying that the app is already running, which is not a big deal for me. 

Hope this isn't too intrusive for you Riccardo.
I attach the patch to this message. Maybe a PR would be better. But I can't do this from my fork of gworkspace : it's polluted with hundreds of fake commits since gnustep transitioned to github.

Here is it : [dockclickpolicy.diff.zip](https://github.com/gnustep/apps-gworkspace/files/7046412/dockclickpolicy.diff.zip)

**Comment by rmottola** [comment]
As written per email, I completely rewrote your patch, taking inspiration from it.
Please test it in the https://github.com/gnustep/apps-gworkspace/tree/singleclick branch.

- Explicit single-click launch  preference
- Behavior extended to both Dock & Tabbed Shelf
- Applies dynamically without restart!

**Comment by BertrandDekoninck** [comment]
No issue detected here with this patch. great job.

**Comment by rmottola** [comment]
Some further refinements were needed, but should finally be done.
