### ISSUE TITLE
Disable "minimized application" icons

### ISSUE THREAD

**Issue by probonopd** [gnustep/apps-gworkspace#8]
Can the "minimized application" icons be disabled?

What are they good for when there is a Dock?

![image](https://user-images.githubusercontent.com/2480569/93721512-18048300-fb91-11ea-8f3c-583a68736b79.png)

Reference:
https://github.com/furybsd/furybsd-livecd/issues/189#issuecomment-695825093

**Comment by rmottola** [comment]
The icons are though to be used for WindowMaker, they are not an exact clone of the Dock 8actually, due to the Dock limitations).
They don't come from GWorkspace, but are one for each application you have launched, they come from GNUstep.

They can be disabled. You can set "GSSuppressAppIcon" to YES. Easiest is using SystemPreferences, otherwise "defaults write NSGlobalDomain GSUseIconManager NO" should do it.

**Comment by probonopd** [comment]
Overall, I think WindowMaker and the rest of the system don't feel consistent. Maybe one should replace WindowMaker altogether.

**Comment by rmottola** [comment]
That's your opinion. GNUstep supports well WindowMaker and has special features to support it. If your windowmanager of choice deviates you have options to disable it. You can replace it and work with it.
Your original question was about how to disable the icons when clearly not using WindowMaker icons and I gave you an option  so you already "replaced" it. Use it or not? your choice, configurations give the freedom to disable features with... "inferior" windowmanager.
In my opinion, WindowMaker is the best around for the experience I need and have come not close to anything in recreating the OpenStep Workspace
